name: Discord Push Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            🚀 Novo push na branch main!
            👤 Autor: ${{ github.actor }}
            📝 Commit: ${{ github.event.head_commit.message }}